### ISSUE TITLE
University courses survey

### ISSUE THREAD

**Issue by alexchmykhalo** [PLLUG/pllug#14]
Prepare survey that will show real situation with programming courses in universities across Lviv.
Information to gather:
- Name of the programming course \ how much time last
- Students feedback about the course
- Approx. effectiveness of course (need to think how to measure it)
- Course program (if available - including labs, list of topics covered, lecture notes etc.)

**Comment by vshevchyk** [comment]
What do we need this survey for? Who will be asked to fill the survey?

**Comment by alexchmykhalo** [comment]
Closed, as this task is outdated and not relevant anymore.
