### ISSUE TITLE
Access to Facebook page for branch leaders

### ISSUE THREAD

**Issue by lavriv92** [PLLUG/pllug#18]

**Comment by TeslyukTaras** [comment]
Taras Teslyuk - Android - https://www.facebook.com/taras.teslyuk.5

**Comment by vbidziura** [comment]
якщо мене треба то я тут https://www.facebook.com/vbidziura

**Comment by lavriv92** [comment]
@TeslyukTaras, @neaptolem  and @vbidziura was added

**Comment by alexchmykhalo** [comment]
Access for Andriy Kovalchuk also should be added (C# Roadmap)

**Comment by alexchmykhalo** [comment]
@lavriv92 last comment still need an action
